name: Deploy Cloud Function

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: AvistaIngestFlights
          runtime: go113
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          timeout: 180
          region: australia-southeast1
          entry_point: AvistaIngestFlights
          env_vars: GOOGLE_PROJECT=${{ secrets.GOOGLE_PROJECT }},GOOGLE_BUCKET=${{ secrets.GOOGLE_BUCKET }},GOOGLE_FOLDER=${{ secrets.GOOGLE_FOLDER }},AVIATION_STACK_API_KEY=${{ secrets.AVIATION_STACK_API_KEY }}